trigger:
  - master
          
pool:
  vmImage: windows-latest
  
jobs:
- job: determine_changes
  displayName: Determine paths changed to understand jobs to run
  steps:
    - powershell: |
        #Get changed files
        $changedFiles = git diff --name-status HEAD HEAD^ 

        #Get config file to determine paths and jobs to check
        $config = Get-Content config.json | ConvertFrom-Json
        foreach ($job in $config.jobs)
        {
            $name = $job.name
            $path = $job.path
            $changed = $null

            if ($job.state){
            $changed = $job.state
            } else {
            $changed = ((Select-String -InputObject $changedFiles -Pattern $path -AllMatches).Matches.Count -gt 0)
            }
            Write-Host "##vso[task.setvariable variable=$name;isOutput=true;]$changed"
            Write-Host "vso[task.setvariable variable=$name;isOutput=true;]$changed"
        }
      name: check_modified

- job: Runs_when_Files_path_changed
  dependsOn: determine_changes
  variables: 
    filesChanged: $[ dependencies.determine_changes.outputs['check_modified.FilesChanged'] ]
  condition: eq(variables.filesChanged, 'True')
  steps:
    - powershell: Write-Host (Get-Content Files/example.txt)

- job: Runs_when_Services_path_changed
  dependsOn: determine_changes
  variables: 
    servicesChanged: $[ dependencies.determine_changes.outputs['check_modified.ServicesChanged'] ]
  condition: eq(variables.servicesChanged, 'True')
  steps:
    - powershell: Write-Host (Get-Content Services/example.txt)